spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: shops-service
          uri: lb://shops-service
          predicates:
            - Path=/api/shops/**
          filters:
            - StripPrefix=2
            #            - name: RequestRateLimiter
            #              args:
            #                redis-rate-limiter.replenishRate: 20
            #                redis-rate-limiter.burstCapacity: 40
            - name: CircuitBreaker
              args:
                name: ShopsCircuitBreaker
                fallbackUri: forward:/fallbacks/shopFallback
        - id: purchase-service
          uri: lb://purchase-service
          predicates:
            - Path=/api/purchase/**
          filters:
            - StripPrefix=2
            #            - name: RequestRateLimiter
            #              args:
            #                redis-rate-limiter.replenishRate: 200
            #                redis-rate-limiter.burstCapacity: 400
            - name: CircuitBreaker
              args:
                name: PurchaseCircuitBreaker
                fallbackUri: forward:/fallbacks/purchaseFallback
        - id: factory-service
          uri: lb://factory-service
          predicates:
            - Path=/api/factory/**
          filters:
            - StripPrefix=2
            #            - name: RequestRateLimiter
            #              args:
            #                redis-rate-limiter.replenishRate: 200
            #                redis-rate-limiter.burstCapacity: 400
            - name: CircuitBreaker
              args:
                name: PurchaseCircuitBreaker
                fallbackUri: forward:/fallbacks/factoryFallback
#  redis:
#    host: 000.00.0.0

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3