spring:
  cloud:
      ribbon:
        enabled: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${random.uuid}