spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      jdbc:
        time_zone: Europe/Moscow
      # create-drop only for tests
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATASOURCE_ADDR}:${DATASOURCE_PORT}/${DATASOURCE_DB}?useLegacyDatetimeCode=false
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  cloud:
    loadbalancer:
      cache:
        ttl: 1s

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      shops-service:
        readTimeout: 500
        connectTimeout: 500
        loggerLevel: full