server:
  port: 8082

spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      # create-drop only for tests
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  cloud:
    loadbalancer:
      cache:
        ttl: 1s

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.uuid}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3