server:
  port: ${CONFIG_SERVER_PORT}

spring:
  output.ansi.enabled: ALWAYS
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      disovery:
        enabled: true
        serviceId: config-server
      server:
        native:
          searchLocations: classpath:/config-repo

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.uuid}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_ADDR}:${EUREKA_SERVER_PORT}/eureka